# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171104_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
