# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
            preserve_default=False,
        ),
    ]
