# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_user_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
