# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20171111_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
