# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171111_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
