# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20171111_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='poll'),
        ),
    ]
