# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_elector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='request_role_change',
            field=models.BooleanField(default=False, help_text='Designates whether the user has requested role change', verbose_name='role change'),
        ),
    ]
